dist: bionic
addons:
  apt:
    packages:
    - cmake
    - valgrind
matrix:
  fast_finish: true
  include:
  - language: rust
    os: linux
    rust: 1.37.0
  - language: rust
    os: linux
    rust: stable
  - language: rust
    os: osx
    osx_image: xcode10.1
    rust: stable

before_script:
- rustup component add clippy
- rustup component add rustfmt
script: ci/script.sh
